### ISSUE TITLE
Updating ARCmanager articles

### ISSUE THREAD

**Issue by akirbis** [akirbis/nfdi4plants.knowledgebase#1]
## Short description

Since we added the first full set of ARCmanager knowledgebase articles, new functions have been added to the service which need to be documented.

This issue will be used to collect undocumented features and track their addition to the articles. 

## Link collection

ARCmanager URL: https://nfdi4plants.de/arcmanager/app/index.html

ARCmanager frontend repo: https://github.com/nfdi4plants/arcmanager_frontend
ARCmanager backend repo: https://github.com/nfdi4plants/arcmanager_backend

Knowledgebase articles: https://www.nfdi4plants.de/nfdi4plants.knowledgebase/docs/ARCmanager-manual/00_index.html

## List of undocumented features

- [x] new ARC validation function
- [x] repository branch support in ARC view
- [x] new function to move annotation table columns
- [x] session timer/session timeout
- [ ] datamap support
- [x] PDF viewer
- [x] Group support when creating ARCs
- [x] Folder creation, renaming and deletion

**Comment by Lu98Be** [comment]
Most new features are documented now (except of the different small features locked behind the experimental area, such as template editor, arc search and more).

The datamap support is also currently part of the experimental area, therefore I haven't added it to the documentation, because it's not even used really so far. Only defined in the Arc specifications.

**Comment by akirbis** [comment]
Can you add a bit more information about the session timer? E.g. what happens when it expires and how to refresh it

https://github.com/akirbis/nfdi4plants.knowledgebase/blob/b821f3a56e2726c14503810ecd3c672d5e44277d/src/docs/ARCmanager-manual/02_login.md?plain=1#L91C1-L98C25

**Comment by Lu98Be** [comment]
I added some more <a href="https://github.com/akirbis/nfdi4plants.knowledgebase/commit/50ddc388633888ab2dc741a14cc343dd3a28e55c" target="_blank">info</a> here. Feel free to edit or extend more if you want (though its just a timer, nothing special ^^).

**Comment by akirbis** [comment]
My thinking was, that people might not be familiar with the session concept and wonder what the timer is about. The most important points should be covered now with your additions.

I will counter-check all additions one more time and test if everything renders properly and then initiate the pull request for the main repository of the knowledgebase.

Thank you all. This issue is closed for now, unless there is more to discuss.
